### ISSUE TITLE
Alltid nyheter virker ikke

### ISSUE THREAD

**Issue by S10ansen** [Pomdre/NRK-radio-discord-bot#2]
Hei, når vi forsøker å bruke !nrk lytt alltid nyheter gir botten svaret "alltid er ikke en gyldig tjener!"
Kanskje gjøre det om til bare "nyheter"?

Digger boten ellers.

**Comment by Pomdre** [comment]
Tusen takk det var kjekt å høre og få tilbakemeldinger!
Den skal nå bare hete nyheter og ikke alltid nyheter 👍 
65dfcc6
